/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bnESc3TseEAaV8kihUXG9L
// Component: _Ti5WiJ9Lowu

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import PageLayout from "../../PageLayout"; // plasmic-import: M_5UdzRD_RWf/component
import MetricCard from "../../MetricCard"; // plasmic-import: Bsr6RApEru4p/component
import { SimpleChart } from "@plasmicpkgs/react-chartjs-2";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { RichTable } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariants_6Vmip6B0Tli5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6vmip6b0TLI5/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: bnESc3TseEAaV8kihUXG9L/projectcss
import sty from "./PlasmicDashboard.module.css"; // plasmic-import: _Ti5WiJ9Lowu/css

createPlasmicElementProxy;

export type PlasmicDashboard__VariantMembers = {};
export type PlasmicDashboard__VariantsArgs = {};
type VariantPropType = keyof PlasmicDashboard__VariantsArgs;
export const PlasmicDashboard__VariantProps = new Array<VariantPropType>();

export type PlasmicDashboard__ArgsType = {};
type ArgPropType = keyof PlasmicDashboard__ArgsType;
export const PlasmicDashboard__ArgProps = new Array<ArgPropType>();

export type PlasmicDashboard__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  section?: Flex__<"section">;
  button?: Flex__<typeof AntdButton>;
  text?: Flex__<"div">;
  positions?: Flex__<typeof RichTable>;
};

export interface DefaultDashboardProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDashboard__RenderFunc(props: {
  variants: PlasmicDashboard__VariantsArgs;
  args: PlasmicDashboard__ArgsType;
  overrides: PlasmicDashboard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "positions.selectedRowKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKey", RichTable_Helpers)
      },
      {
        path: "positions.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRow", RichTable_Helpers)
      },
      {
        path: "positions.selectedRows",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRows", RichTable_Helpers)
      },
      {
        path: "positions.selectedRowKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKeys", RichTable_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    positions: usePlasmicDataOp(() => {
      return {
        sourceId: "bBmyZdYQJ2uh5nJ4b92zAb",
        opId: "8c01f506-5874-43f3-95d3-af9e506c1fa3",
        userArgs: {},
        cacheKey: `plasmic.$.8c01f506-5874-43f3-95d3-af9e506c1fa3.$.`,
        invalidatedKeys: null,
        roleId: "b44c13f7-38fe-451d-8d0d-1f97f925bb1f"
      };
    }),
    candidates: usePlasmicDataOp(() => {
      return {
        sourceId: "bBmyZdYQJ2uh5nJ4b92zAb",
        opId: "41e934bd-6c28-4f35-b7e5-6082b2de9ffb",
        userArgs: {},
        cacheKey: `plasmic.$.41e934bd-6c28-4f35-b7e5-6082b2de9ffb.$.`,
        invalidatedKeys: null,
        roleId: "b44c13f7-38fe-451d-8d0d-1f97f925bb1f"
      };
    }),
    hires: usePlasmicDataOp(() => {
      return {
        sourceId: "bBmyZdYQJ2uh5nJ4b92zAb",
        opId: "4843aeb5-dff4-4f23-bc0f-dac92caffe50",
        userArgs: {},
        cacheKey: `plasmic.$.4843aeb5-dff4-4f23-bc0f-dac92caffe50.$.`,
        invalidatedKeys: null,
        roleId: "b44c13f7-38fe-451d-8d0d-1f97f925bb1f"
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6Vmip6B0Tli5()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <DataCtxReader__>
              {$ctx => (
                <section
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  className={classNames(projectcss.all, sty.section)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oiYht)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__ytCg3
                      )}
                    >
                      {"Loan Exchange Dashboard"}
                    </h4>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dtBzP)}
                    >
                      <MetricCard
                        className={classNames(
                          "__wab_instance",
                          sty.metricCard__bbCbr
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.positions.data.length;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "#";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </MetricCard>
                      <MetricCard
                        className={classNames(
                          "__wab_instance",
                          sty.metricCard__bNeAl
                        )}
                        slot={"Active Candidates"}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.candidates.data.filter(
                                c =>
                                  !c.status?.match(
                                    /Offer accepted|Offer declined|Reject before offer/
                                  )
                              ).length;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "#";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </MetricCard>
                      <MetricCard
                        className={classNames(
                          "__wab_instance",
                          sty.metricCard__bvsOy
                        )}
                        slot={"Employee Referrals"}
                      >
                        {"46"}
                      </MetricCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hDuKc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nLcwO
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__sc7Z4
                          )}
                        >
                          {"Interview-to-Hire Ratio"}
                        </h4>
                        <p
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.__wab_text,
                            sty.p__izTg
                          )}
                        >
                          {"Jan 1, 2023 - June 30, 2023"}
                        </p>
                        <SimpleChart
                          className={classNames(
                            "__wab_instance",
                            sty.chart___3Fq1V
                          )}
                          data={(() => {
                            const byDept = ((
                              x = $queries.candidates.data,
                              f = c =>
                                $queries.positions.data.find(
                                  p => p.id === c.position_id
                                )?.dept,
                              r = {}
                            ) => (
                              x.forEach(v => (r[f(v)] ??= []).push(v)), r
                            ))();

                            for (const key in byDept) {
                              byDept[key] =
                                byDept[key]
                                  .map(a => a.status === "Offer accepted")
                                  .reduce((a, b) => a + b) / byDept[key].length;
                            }

                            return Object.entries(byDept).map(([k, v]) => ({
                              dept: k,
                              ratio: v
                            }));
                          })()}
                          interactive={true}
                          labelField={"dept"}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kiwd1
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__ti2Fo
                          )}
                        >
                          {"Applicant flow"}
                        </h4>
                        <p
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.__wab_text,
                            sty.p__lbc2U
                          )}
                        >
                          {"Jan 1, 2023 - June 30, 2023"}
                        </p>
                        <SimpleChart
                          className={classNames(
                            "__wab_instance",
                            sty.chart__edOsz
                          )}
                          data={$queries.hires.data}
                          type={"line"}
                        />
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8E8LT
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jaO4Y
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__w8Ybc
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__wwUts
                            )}
                          >
                            {"Top Job Postings"}
                          </h4>
                          <p
                            className={classNames(
                              projectcss.all,
                              projectcss.p,
                              projectcss.__wab_text,
                              sty.p__mNSmp
                            )}
                          >
                            {
                              "View the top job listings across your organization based on applicant numbers, views, and interview progress."
                            }
                          </p>
                        </div>
                        <AntdButton
                          data-plasmic-name={"button"}
                          data-plasmic-override={overrides.button}
                          className={classNames("__wab_instance", sty.button)}
                          size={"large"}
                          type={"primary"}
                        >
                          <div
                            data-plasmic-name={"text"}
                            data-plasmic-override={overrides.text}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text
                            )}
                          >
                            {"Add a job"}
                          </div>
                        </AntdButton>
                      </div>
                      {(() => {
                        const child$Props = {
                          className: classNames(
                            "__wab_instance",
                            sty.positions
                          ),
                          data: (() => {
                            try {
                              return $queries.positions;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          defaultSize: hasVariant(
                            globalVariants,
                            "screen",
                            "mobileOnly"
                          )
                            ? "small"
                            : undefined,
                          fields: (() => {
                            const __composite = [
                              { key: "id", fieldId: "id", isHidden: null },
                              { key: "title", fieldId: "title" },
                              {
                                key: "description",
                                fieldId: "description",
                                isHidden: null
                              },
                              {
                                key: "department_id",
                                fieldId: "department_id",
                                title: null,
                                isHidden: null
                              },
                              {
                                key: "archived",
                                fieldId: "archived",
                                isHidden: null
                              },
                              { key: "created_at", fieldId: "created_at" },
                              { key: "dept", fieldId: "dept" },
                              {
                                key: "num_candidates",
                                fieldId: "num_candidates",
                                isHidden: null
                              },
                              {
                                key: "num_active_candidates",
                                fieldId: "num_active_candidates"
                              }
                            ];
                            __composite["0"]["isHidden"] = true;
                            __composite["2"]["isHidden"] = true;
                            __composite["3"]["title"] = "dept";
                            __composite["3"]["isHidden"] = true;
                            __composite["4"]["isHidden"] = true;
                            __composite["7"]["isHidden"] = true;
                            return __composite;
                          })(),

                          onRowSelectionChanged: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRowKey",
                              ["positions", "selectedRowKey"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRow",
                              ["positions", "selectedRow"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRows",
                              ["positions", "selectedRows"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRowKeys",
                              ["positions", "selectedRowKeys"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                          },
                          pageSize: 20,
                          scopeClassName: sty["positions__instance"],
                          selectedRowKey: generateStateValueProp($state, [
                            "positions",
                            "selectedRowKey"
                          ]),
                          selectedRowKeys: generateStateValueProp($state, [
                            "positions",
                            "selectedRowKeys"
                          ]),
                          themeResetClassName: classNames(
                            projectcss.root_reset,
                            projectcss.root_reset_tags,
                            projectcss.plasmic_default_styles,
                            projectcss.plasmic_mixins,
                            projectcss.plasmic_tokens,
                            plasmic_antd_5_hostless_css.plasmic_tokens,
                            plasmic_plasmic_rich_components_css.plasmic_tokens
                          )
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "selectedRowKey",
                              plasmicStateName: "positions.selectedRowKey"
                            },
                            {
                              name: "selectedRow",
                              plasmicStateName: "positions.selectedRow"
                            },
                            {
                              name: "selectedRows",
                              plasmicStateName: "positions.selectedRows"
                            },
                            {
                              name: "selectedRowKeys",
                              plasmicStateName: "positions.selectedRowKeys"
                            }
                          ],
                          [],
                          RichTable_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <RichTable
                            data-plasmic-name={"positions"}
                            data-plasmic-override={overrides.positions}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  </div>
                </section>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "section", "button", "text", "positions"],
  pageLayout: ["pageLayout", "section", "button", "text", "positions"],
  section: ["section", "button", "text", "positions"],
  button: ["button", "text"],
  text: ["text"],
  positions: ["positions"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  section: "section";
  button: typeof AntdButton;
  text: "div";
  positions: typeof RichTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDashboard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDashboard__VariantsArgs;
    args?: PlasmicDashboard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDashboard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicDashboard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDashboard__ArgProps,
          internalVariantPropNames: PlasmicDashboard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDashboard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDashboard";
  } else {
    func.displayName = `PlasmicDashboard.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={"b44c13f7-38fe-451d-8d0d-1f97f925bb1f"}
      appId={"bnESc3TseEAaV8kihUXG9L"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "bnESc3TseEAaV8kihUXG9L"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicDashboard = Object.assign(
  // Top-level PlasmicDashboard renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    section: makeNodeComponent("section"),
    button: makeNodeComponent("button"),
    text: makeNodeComponent("text"),
    positions: makeNodeComponent("positions"),

    // Metadata about props expected for PlasmicDashboard
    internalVariantProps: PlasmicDashboard__VariantProps,
    internalArgProps: PlasmicDashboard__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDashboard;
/* prettier-ignore-end */
